- name: Elasticsearch ocpdes
  hosts: master
  roles:
    - role: elastic.elasticsearch
  vars:
    es_version: 8.2.3
    es_api_basic_auth_username: elastic
    es_api_basic_auth_password: changeme
    es_enable_http_ssl: true
    es_enable_transport_ssl: true
    es_ssl_keystore: "files/certs/my-keystore.p12"
    es_ssl_truststore: "files/certs/my-keystore.p12"
    es_ssl_keystore_password: test
    es_ssl_truststore_password: test
    es_validate_certs: no
    es_instance_name: "ocpdes"
    es_log_dir: "/var/log/elasticsearch"
    es_heap_size: 4g
    es_java_install: true
    es_start_service: true
    es_api_host: "{{ inventory_hostname }}"
    es_api_port: 9200
    es_enable_auto_ssl_configuration: true
    es_plugins:
     - plugin: ingest-attachment
     - plugin: repository-s3
    es_node_roles:
    - master
    - data
    - ingest
    es_data_dirs:
      - "/data"
    es_config:
      cluster.name: "ocpdes"
      network.host: eth1
      http.port: 9200
      transport.port: 9300
      node.name: "{{ inventory_hostname }}"
      bootstrap.memory_lock: true
      xpack.license.self_generated.type: trial
      xpack.security.enrollment.enabled: true
      discovery.seed_hosts: "elastic-one.192.168.1.210.nip.io:9300,elastic-two.192.168.1.211.nip.io:9300,elastic-three.192.168.1.212.nip.io:9300"
      cluster.initial_master_nodes: "elastic-one.192.168.1.210.nip.io,elastic-two.192.168.1.211.nip.io,elastic-three.192.168.1.212.nip.io"